# https://github.com/gautamkrishnar/keepalive-workflow

name: Github Action with a cronjob trigger

on:
  # 0:30 AM UTC every Saturday
  schedule:
    - cron: "30 0 * * *"

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
