# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  # 1:15 AM UTC on the 16th of each month
  schedule:
    - cron: '15 1 16 * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update
      run: |
        sudo apt-get update

    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Add ~/.local/bin to PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python3 --version
        python3 -m pip install --upgrade pip
        python3 -m pip install --user flake8 pytest
        if [ -f requirements.txt ]; then python3 -m pip install --user -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install Chromium-driver
      run: |
        sudo apt-get -y install chromium-chromedriver

    - name: Run Python3month
      run: |
        python3 -m pip install --user ./
        export XDG_DATA_HOME=$HOME
        echo "username: ${{ secrets.USERNAME }}" >> "$XDG_DATA_HOME/pythonanywhere_credentials.yaml"
        echo "password: ${{ secrets.PASSWORD }}" >> "$XDG_DATA_HOME/pythonanywhere_credentials.yaml"
        pythonanywhere_3_months -Hc $(which chromedriver)
